### ISSUE TITLE
warning: this decimal constant is unsigned only in ISO C90

### ISSUE THREAD

**Issue by smits** [ros/gencpp#16]
I get this warning on an ARM HF system for all unsigned constants in a msg description: 

msg:

```
uint32 ALL = 4294967295
```

The generated code for this constant is:

```
enum { ALL = 4294967295 };
```

and should be

```
enum { ALL = 4294967295u };
```

to get rid of this warning.

**Comment by dirk-thomas** [comment]
Can you please verify that PR #17 fixes the warning for your specific system?

**Comment by meyerj** [comment]
Hi Dirk,

with the version of the pull request I got compile errors in hydro because of the removed `__connection_header` member in 2c3d57bdb93bda2c5828d80b848601e57b8e7f08:

```
/opt/ros/hydro/include/ros/serialization.h: In function 'void ros::assignSubscriptionConnectionHeader(T*, const boost::shared_ptr<std::map<std::basic_string<char>, std::basic_string<char> > >&, typename boost::enable_if<ros::message_traits::IsMessage<T> >::type*) [with T = im_msgs::State_<std::allocator<void> >, typename boost::enable_if<ros::message_traits::IsMessage<T> >::type = void]':
/opt/ros/hydro/include/ros/subscription_callback_helper.h:124:5:   instantiated from 'ros::VoidConstPtr ros::SubscriptionCallbackHelperT<P, Enabled>::deserialize(const ros::SubscriptionCallbackHelperDeserializeParams&) [with P = const im_msgs::State_<std::allocator<void> >&, Enabled = void, ros::VoidConstPtr = boost::shared_ptr<const void>]'
/opt/ros/hydro/include/ros/serialization.h:932:3: error: 'struct im_msgs::State_<std::allocator<void> >' has no member named '__connection_header'
```

After having readded this shared pointer to `msg.h.template` compilation is successful without warnings, at least for the `uint32` example shown above.

**Comment by dirk-thomas** [comment]
Indeed, you either have to test the pull request against the other indigo sources or apply the same patch to the hydro/groovy source code of gencpp.

Thanks for verifying that it gets rid of the warning for you.
