### ISSUE TITLE
Undefined reference for string constant in service

### ISSUE THREAD

**Issue by markusachtelik** [ros/gencpp#2]
Hi,

I originally posted this here:  http://answers.ros.org/question/49422/undefined-reference-for-string-constant-in-service/ ,  then submitted a ticket here: https://code.ros.org/trac/ros-pkg/ticket/5587, so I hope this is in the right place here now ;)

when I define a simple service in Fuerte, e.g.

```
string my_string
string CONST_STRING=some_value

---
```

I get an undefined reference to ...::CONST_STRING during linking. Looking at the generated header file, I noticed that CONST_STRING gets declared, but never defined. I tested the same with messages: here it works fine and I can see the definition of CONST_STRING.

The same applies for floatXX-- I guess that problem exists for every constant that can not be encoded into an enum.

Best, Markus

**Comment by dirk-thomas** [comment]
The generation of messages and services uses the same code path so it is unlikely that they behave differently, I compared both generated files (from a message and a service with your posted code) and they look ok (and linked fine for me).

Can you please provide a mini example (i.e. just main() function using the message/service) which shows the described linking error?

**Comment by markusachtelik** [comment]
Hi, 

thanks for your reply! This also seems strange to me as I also assumed that they should use the same code path. 
I just tested it again in a minimal example and a fresh and clean package. I created both a message and a service:

msg: 

```
string test_string=some_string
```

srv: 

```
string test_string=some_string
---
```

main.cpp:

```
#include <service_test/TestMsg.h>
#include <service_test/TestSrv.h>
#include <iostream>

int main(){

  std::cout<<"message: "<<service_test::TestMsg::test_string<<std::endl;
  std::cout<<"service: "<<service_test::TestSrv::Request::test_string<<std::endl;
  return 0;
}
```

That gives me the following linker error:

```
undefined reference to `service_test::TestSrvRequest_<std::allocator<void> >::test_string'
```

I checked the generated header files, for the message, I can find the following initialization for test_string (l. 43 in my header file):

```
template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  TestMsg_<ContainerAllocator>::test_string = "some_string";
```

However, I can't find anything like that in the header file for the service. 
I'm on fuerte and just updated everything. `rosversion gencpp` tells me 0.3.4 . That sounds relatively old since I saw that the latest tag is 0.4.10. `which gen_cpp.py` points to /opt/ros/fuerte/bin/gen_cpp.py . Is there any other version information that you need?

Thanks a lot for the help!
Markus

**Comment by dirk-thomas** [comment]
A fix has been committed to the fuerte-devel and groovy-devel branch.
