### ISSUE TITLE
Generated Messages Attribute Copyright to Willow Garage

### ISSUE THREAD

**Issue by chadrockey** [ros/gencpp#20]
https://github.com/ros/gencpp/blob/indigo-devel/scripts/msg.h.template#L17

The BSD license still attributes copyright to Willow Garage for auto generated message files.  Should this (can this) be changed?

**Comment by dirk-thomas** [comment]
The code was originally written at Willow Garage. Therefore I don't see a reason why the copyright line should be changed?

**Comment by chadrockey** [comment]
This is the template for all generated messages.

So for instance, if I generate my_msgs/Foo.msg, then the generated .h file has the copyright attributed to Willow Garage in 2011.

I'm not extremely well versed in license isssues, so I don't know if there's any reason to change this or not.  Should the year or the ROS guardian institution be updated?

**Comment by kwc** [comment]
IANAL, but I wonder if there should be a header at all. There is a school of thought that the header is redundant WRT license/copyright, and it also is incorrect that the generated code could change copyright assignment/license of the original msg/srv.

IIRC, protobufs don't do any header other than:

// Generated by the protocol buffer compiler.  DO NOT EDIT!
