### ISSUE TITLE
Remove _connection_header from message

### ISSUE THREAD

**Issue by kwatts** [ros/gencpp#3]
ROS messages have a shared pointer to a `_connection_header` in the message. This field is unused, and takes a large amount of space (8 bytes on 64bit systems). We should remove this field to make using ROS messages easier.

From the "msg.h.template" file:

``` c++
// REMOVE THIS FIELD
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
```

**Comment by kwatts** [comment]
The __connection_header field is used in topic_tools, but it should be easy to replace. Simply use "MessageEvent" instead of an actual ROS message in the subscription.

http://ros.org/wiki/roscpp/Overview/Publishers%20and%20Subscribers#MessageEvent_.5BROS_1.1.2B-.5D

**Comment by dirk-thomas** [comment]
As far as I can see the field is not unused. Several packages in base ROS currently use it: topic_tools, actionlib, tutorials, etc. Furthermore it would also affect Python which has the same attribute.

Anyway it has not been deprecated before and can therefore not be removed directly.

Where did you find the "remove this field" line? I can't see it in the template (https://github.com/ros/gencpp/blob/master/scripts/msg.h.template#L128).

**Comment by kwatts** [comment]
Sorry, that was just my comment.

Can we start deprecating this field in Groovy so we can fix Heroic?

**Comment by kwatts** [comment]
I propose that we deprecate the connection header now, and remove it after a cycle. I don't see any reason to deprecate or remove it in Python, the performance optimization isn't worth it.

For the packages that do use it, we should transition to MessageEvents. http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers#MessageEvent_.5BROS_1.1.2B-.5D

**Comment by dirk-thomas** [comment]
This will be targeted for _Indigo_.

**Comment by kwatts** [comment]
I've made pull requests to remove all client uses of "__connection_header" in hydro (pulls will have to go into indigo). 

There are three additional things we need to do for this:
- Change/remove the "assignSubscriptionConnectionHeader" function in "serialization.h" and the corresponding function for services in roscpp
- Remove the "__connection_header" field from the message templates.
- Remove the "__connection_header" from the topic_tools::ShapeShifter (which is just a message)

For the first step, do you think it's better to remove the "assignSubscriptionConnectionHeader" or just deprecate it? It's only used in roscpp for serialization, and rosbag_storage.

**Comment by dirk-thomas** [comment]
Fixed by 2c3d57bdb93bda2c5828d80b848601e57b8e7f08. Will address the other locations when releasing into Indigo.

**Comment by wjwwood** [comment]
This was never deprecated in Hydro, which is fine for us since there is a clear alternative, preferred method for getting the information in the connection header, but there may be people out there who might be using it. I really dislike the fact that it was not deprecated in Hydro nor mentioned (that I can see) in the Hydro migration guide and now we are removing it in Indigo.

**Comment by kwatts** [comment]
Unfortunately we weren't able to add a depreciation message in Hydro
without warning when the message was defined (not when the field is used).

This field was clearly left in by mistake (when other fields for md5sum,
etc were removed in C-Turtle). The ros::MessageEvent is the documented and
supported means of getting connection information, and has been for some
time.
