### ISSUE TITLE
Service file, fails to generate service when tab's are used for separation instead of space

### ISSUE THREAD

**Issue by Chris-Bee** [ros/gencpp#30]
Hello,
I hope gencpp generates the headers based on service files and the issue is in the right repo.

I use ros indigo ubuntu 14.04:

When I generate a service file and define it like:

```
int8 <tab> test1
int8 <tab> test2
---
int8 <tab> test3
```

This does result in a compilation error.
If I define it like:

```
int8 .. test1
int8 .. test2
---
int8 .. test3
```
With "." representing "space", the compilation works without an error regarding the service file definition.

Is this intended behaviour?

Best,
Chris

**Comment by dirk-thomas** [comment]
The [spec](http://wiki.ros.org/msg) mentions that the field type and field name must be separated by a space:

> 2.1 Each field consists of a type and a name, separated by a space...

Therefore I consider this intended behavior.
