### ISSUE TITLE
Provider operator== and operator!= for deep comparison between messages

### ISSUE THREAD

**Issue by mikepurvis** [ros/gencpp#33]
I was surprised when I needed this and it wasn't there. It's brittle to test fields manually in my user code and relatively easy to support it here.

**Comment by mikaelarguedas** [comment]
Just to confirm my understanding: you mean adding `operator==` and `operator!=` to the generated message classes, right?

**Comment by mikepurvis** [comment]
Sorry, yes indeed I do. Will fix the title.

**Comment by dirk-thomas** [comment]
Implemented in #41.
