### ISSUE TITLE
Allow free functions in C++ message header plugins

### ISSUE THREAD

**Issue by peci1** [ros/gencpp#39]
Follows #32 .

What about adding `MY_PKG_MESSAGE_MYVECTOR3_PLUGIN_FREE_FUNCTIONS` that would be at (or near) the very end of the header file? That'd allow adding more traits and such things.

@dirk-thomas commented
> Depending on what you mean with free functions you might be able to just put them into the `<pkgname>/plugin/<msgname>.h` file.

But this file is included before the message definition file, so you cannot use the defined class or typedefs in the plugin file...

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request with the proposed feature.

**Comment by dirk-thomas** [comment]
Addressed by #40.
