### ISSUE TITLE
Error in C++ message auto generation in ROS groovy

### ISSUE THREAD

**Issue by drdas** [ros/gencpp#6]
If a comment description line in a .msg file (starting with #) ends in a a special character such as ( ), extra newlines are added in the generated header file which gives compiler errors when included. Example below:

```
# ICD-XXXXX - Delta Position
# Primary Measurement: Change in position over a time interval (1D, 2D, or 3D)
# Standard Header
Header header 
#1, 2, or 3 elements based on dimension specified in metadata
float64[] delta_pos
# Delta position covariance matrix (row-major) in [units^2] of size nDim x nDim.
# The matrix is linearized into a single array for storage.
float64[]  delta_pos_covariance
```

generates the header with the following code (note the extra newlines):

```
template<class ContainerAllocator>
struct Definition< ::MyClass::DeltaPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ICD-XXXXX - Delta Position
\n\
# Primary Measurement: Change in position over a time interval (1D, 2D, or 3D)
\n\

\n\
# Standard Header
\n\
Header header

```

**Comment by tfoote** [comment]
@drdas see the markdown notation link at the top right of the comment box for how to properly quote code.

**Comment by jarvisschultz** [comment]
I was just answering [this question](http://answers.ros.org/question/100301/msg-gen-error-stray-in-program/?answer=100306) on answers.ros.org, and noticed that line endings used in the *.msg files can also break the generated C++ header files.  For example, consider a simple message file

```
Header header
```

If it has only a "\n" line ending, the return string starts with

```
    return "Header header\n\
```

But if it ends in "\r\n" the return string starts with 

```
    return "Header header
\n\
```

Github parses the extra \r in the second one as a carriage return.  A hexdump of the two strings reveals that there is indeed an extra 0x0d character in the second string.

This produces compilation errors like

```
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:174:5: error: missing terminating " character
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘\’ in program
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘\’ in program
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘\’ in program
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘\’ in program
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘\’ in program
/home/jarvis/groovyws/devel/include/pend_tracker/Pose2DArray.h:175:1: error: stray ‘#’ in program
```

I tested this with rosbuild and catkin, and got the same results on both.

**Comment by dirk-thomas** [comment]
I could not reproduce any of the described issues based on the descriptions above. Please provide a file which exhibits the problem for you.

**Comment by jarvisschultz** [comment]
I was actually also unable to reproduce the error of the error of @drdas.  But I am consistently getting the error with the line endings.  I just created a gist repo that contains two message files one with _\r\n_ and one with _\n_.  That repo can be cloned [here](https://gist.github.com/jarvisschultz/a242acf30b08cfe7d1f3). I also put the header files that are generated for each of the message files and a .gitattributes file that prevents git from changing any line endings.

I may not have made this clear, but the compilation error doesn't show up until you try to #include the generated *.h files in a *.cpp file.  To that end, I also put two minimal C++ files and a simple makefile in the repo.  Running `make work` produces a binary with no warnings, and running `make broken` produces the errors I am seeing.

Here is the hexdump showing the difference between the two files:

```
jarvis@vedauwoo:~/Desktop/a242acf30b08cfe7d1f3$ hexdump -C works_test.msg
00000000  48 65 61 64 65 72 20 68  65 61 64 65 72 0a        |Header header.|
0000000e
jarvis@vedauwoo:~/Desktop/a242acf30b08cfe7d1f3$ hexdump -C broken_test.msg
00000000  48 65 61 64 65 72 20 68  65 61 64 65 72 0d 0a     |Header header..|
0000000f
```

Here is the hexdump of the sole differing line in the headers:

```
jarvis@vedauwoo:~/Desktop/a242acf30b08cfe7d1f3$ sed -n '174p' works_test.h |hexdump -C
00000000  20 20 20 20 72 65 74 75  72 6e 20 22 48 65 61 64  |    return "Head|
00000010  65 72 20 68 65 61 64 65  72 5c 6e 5c 0a           |er header\n\.|
0000001d
jarvis@vedauwoo:~/Desktop/a242acf30b08cfe7d1f3$ sed -n '174p' broken_test.h |hexdump -C
00000000  20 20 20 20 72 65 74 75  72 6e 20 22 48 65 61 64  |    return "Head|
00000010  65 72 20 68 65 61 64 65  72 0d 5c 6e 5c 0a        |er header.\n\.|
0000001e
```

**Comment by dirk-thomas** [comment]
Until the fix has been release as a workaround just make sure to save the message file with linux line ending (`\n`).

**Comment by jarvisschultz** [comment]
Ridiculously simple fix.  I should have looked at the source before bothering to write all of the debug info.  Thanks for the fast response!
